# Generated by Django 3.2.18 on 2023-04-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='req_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='sha512 hash'),
        ),
    ]
