class Api::V1::ContactsController < ApplicationController
    # This Rails helper method serves us in this case as it's not making the server asks for a token..
    # when a request is made from the Frontend. Because it's not necessary in this task to have a..
    # encoded tokens generated by Rails Sessions or JWT, this method has been used!
    skip_before_action :verify_authenticity_token, raise: false

    # GET => Idempotent Request (No matter how many times this request is made against the API,
    #        It won't change the server/database 's data)
    def index
        @contacts = Contact.all.order(created_at: :desc)
        respond_to do |format|
            format.json { render json: @contacts }
            format.csv { send_data @contacts.to_csv, filename: "contacts_data.csv" }
        end
    end
    # GET => Idempotent Request (Same as Index method)
    def show
        @contact = Contact.find(params[:id])
        respond_to do |format|
            format.json { render json: @contact }
        end
    end
    # POST => Non-Idempotent Request (POST requests are creating a new record everytime it's made,
    #         Thus, it's affecting the server/database 's data)
    def create
        @contact = Contact.new(contact_params)
        @contact.save
    end
    # PUT => Idempotent Request (PUT requests are changing a record that's already in the server for..
    #        Only one time, after that, no matter how many time it's made! It won't affect the server)
    def update
        @contact = Contact.find(params[:id])
        @contact.update(contact_params)
    end
    # DELETE => Idempotent Request (Same as Update method)
    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy
    end

    private

    def contact_params
        params.require(:contact).permit(:name, :job, :age)
    end
end
